authentications/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
     path('user/', include("user.urls", namespace="user")),
    path('', views.index, name = 'home')
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', views.Register.as_view(), name="register"),
]

user/models.py
from django.db import models

user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

authentications/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'user/index.html')

user/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class Register(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("user:login")
    template_name = "user/register.html"

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
        <div class="container">
          <div class="navbar-nav align-items-center">
            <a class="navbar-brand mynav" href="{% url 'home' %}">authentication system</a>
          </div>
          <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
             <a class="nav-item nav-link" href="{% url 'user:logout' %}" class="btn btn-simple">Log out</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'user:login' %}" class="btn btn-simple">Log in</a>
              <a class="nav-item nav-link" href="{% url 'user:register' %}" class="btn btn-simple">Sign up</a>
            {% endif %}
          </div>
        </div>
    </nav>
</body>
</html>

user/templates/user/login.html
{% load bootstrap3 %}

<h1>Login</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type='submit' class="btn btn-default" value="Login">
</form>

user/templates/user/logout.html
<h1>THANKS FOR VISITING, COME SOON </h1>

user/templates/user/register.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    {% load bootstrap3 %}
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input type='submit' class="btn btn-default" value="Sign Up">
    </form>

    {% block content %}
    {% endblock %}